name: social_sharing_plus_example
description: "Demonstrates how to use the social_sharing_plus plugin."
publish_to: 'none'
version: 1.2.3+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  social_sharing_plus:
    path: ../
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.21

flutter:

  uses-material-design: true
